# Generated by Django 4.2.3 on 2024-12-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('cik', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
