# Generated by Django 4.2.3 on 2024-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
